import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Fuentes de Google cargadas como variables CSS, aplicadas globalmente en <html>
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadatos por defecto del scaffold (pendiente de personalizar para Arcade Vault)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout raíz: envuelve todas las rutas de la app
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
